# Generated by Django 2.0.4 on 2018-04-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180426_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='text',
        ),
    ]
