# Generated by Django 2.0.4 on 2018-04-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180426_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='Name',
        ),
    ]
